# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonFromPlainText
                                 A QGIS plugin
 Extracts coordinates from plain text and creates polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-04-22
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Paweł Strzelewicz
        email                : @
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .polygon_from_plain_text_dialog import PolygonFromPlainTextDialog
import os.path
import datetime
from .aviation_gis_toolkit.coordinate_extraction import *
from .aviation_gis_toolkit.coordinate_predetermined import *


class PolygonFromPlainText:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        self.pair_order = None
        self.pair_format = None
        self.pair_separator = None
        self.coord_finder = None
        self.lyr_name = None

        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PolygonFromPlainText_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = PolygonFromPlainTextDialog()

        self.dlg.comboBoxOrder.currentIndexChanged.connect(self.get_pair_regex)
        self.dlg.comboBoxFormat.currentIndexChanged.connect(self.get_pair_regex)
        self.dlg.comboBoxSeparator.currentIndexChanged.connect(self.get_pair_regex)
        self.dlg.pushButtonCreatePolygon.clicked.connect(self.create_polygon)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&PolygonFromPlainText')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'PolygonFromPlainText')
        self.toolbar.setObjectName(u'PolygonFromPlainText')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PolygonFromPlainText', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/polygon_from_plain_text/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'PolygonFromPlainText'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&PolygonFromPlainText'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def set_pair_order(self):
        """ Sets coordinate order. """
        if self.dlg.comboBoxOrder.currentIndex() == 0:
            self.pair_order = None
        if self.dlg.comboBoxOrder.currentIndex() == 1:
            self.pair_order = LL_ORDER_LONLAT
        elif self.dlg.comboBoxOrder.currentIndex() == 2:
            self.pair_order = LL_ORDER_LATLON

    def set_pair_format(self):
        """ Sets coordinate format. """
        if self.dlg.comboBoxFormat.currentIndex() == 0:
            self.pair_format = None
        elif self.dlg.comboBoxFormat.currentIndex() == 1:
            self.pair_format = AF_DMSH_COMP
        elif self.dlg.comboBoxFormat.currentIndex() == 2:
            self.pair_format = AF_HDMS_COMP
        elif self.dlg.comboBoxFormat.currentIndex() == 3:
            self.pair_format = DMSH_SEP
        elif self.dlg.comboBoxFormat.currentIndex() == 4:
            self.pair_format = HDMS_SEP

    def set_pair_separator(self):
        """ Sets coordinate pair separator. """
        if self.dlg.comboBoxSeparator.currentIndex() == 0:
            self.pair_separator = None
        elif self.dlg.comboBoxSeparator.currentIndex() == 1:  # Null separator
            self.pair_separator = LL_SEP_NONE
        elif self.dlg.comboBoxSeparator.currentIndex() == 2:  # Space
            self.pair_separator = LL_SEP_SPACE
        elif self.dlg.comboBoxSeparator.currentIndex() == 3:  # Hyphen
            self.pair_separator = LL_SEP_HYPHEN
        elif self.dlg.comboBoxSeparator.currentIndex() == 4:
            self.pair_separator = LL_SEP_SLASH
        elif self.dlg.comboBoxSeparator.currentIndex() == 5:
            self.pair_separator = LL_SEP_BACKSLASH

    def get_pair_regex(self):
        self.set_pair_order()
        self.set_pair_format()
        self.set_pair_separator()
        # Pair separator might be empty string
        if self.pair_order and self.pair_format and self.pair_separator is not None:

            self.coord_finder = CoordinatePairExtraction(self.pair_order, self.pair_format, self.pair_separator)
            sample_format = self.coord_finder.get_coordinate_pair_example()
            self.dlg.labelSampleCoordPair.setText(sample_format)
        else:
            self.dlg.labelSampleCoordPair.setText("Select to see format example")
            self.coord_finder = None

    def extract_coordinates(self):
        raw_text = self.dlg.textEditPolygonPlainText.toPlainText()
        coords = self.coord_finder.get_coordinate_pair_list(raw_text)
        return coords

    @staticmethod
    def gen_name():
        """ Generates name for memory layer base on timestamp in format:
        YYYYY_MMM_DDD_HHMM.ssssss, e.g.: 2020_Apr_Wed_1622.000001. """
        timestamp = datetime.datetime.now()
        return timestamp.strftime('%Y_%b_%a_%H%M.%f')

    @staticmethod
    def create_memory_lyr(lyr_name):
        """ Create temporary 'memory' layer to store results of calculations.
        :param lyr_name: string, layer name
        :return mem_lyr: created memory layer
        """
        mem_lyr = QgsVectorLayer('Polygon?crs=epsg:4326', lyr_name, 'memory')
        prov = mem_lyr.dataProvider()
        mem_lyr.startEditing()
        prov.addAttributes([QgsField("POL_ID", QVariant.String)])
        mem_lyr.commitChanges()
        QgsProject.instance().addMapLayer(mem_lyr)
        return mem_lyr

    @staticmethod
    def add_polygon_to_layer(polygon_id, feat, prov, vertices):
        """ Adds polygon to feature.
        :param polygon_id: str, ident of polygon
        :param feat: Qgsfeature
        :param prov: QgsProvider
        :param vertices: list of QgsPoint which form polygon
        """
        if polygon_id is not None and len(vertices) < 3:
            # Need at least 3 vertices to create polygon
            # TODO: Log error message
            pass
        else:
            # Add polygon to layer
            if polygon_id is not None:
                feat.setGeometry(QgsGeometry.fromPolygonXY([vertices]))
                feat.setAttributes([polygon_id])
                prov.addFeature(feat)

    def create_polygon(self):
        if self.coord_finder:
            coords = self.extract_coordinates()

            if self.lyr_name:
                lyr = QgsProject.instance().mapLayersByName(self.lyr_name)[0]
            else:
                self.lyr_name = self.gen_name()
                lyr = self.create_memory_lyr(self.lyr_name)

            prov = lyr.dataProvider()
            feat = QgsFeature()

            lon = CoordinatePredetermined(ang_type=AT_LON, ang_format=self.pair_format)
            lat = CoordinatePredetermined(ang_type=AT_LAT, ang_format=self.pair_format)

            vertices = []  # List of vertices for current polygon, QgsPoints
            for coord in coords:
                if self.pair_order == LL_ORDER_LONLAT:
                    lon_dd = lon.coordinate_to_dd(coord[0])
                    lat_dd = lat.coordinate_to_dd(coord[1])
                elif self.pair_order == LL_ORDER_LATLON:
                    lon_dd = lon.coordinate_to_dd(coord[1])
                    lat_dd = lat.coordinate_to_dd(coord[0])

                vertex = QgsPointXY(lon_dd, lat_dd)
                vertices.append(vertex)

            self.add_polygon_to_layer('1', feat, prov, vertices)

    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
